# TODO: make up a better and more versatile config
nodes:
  - node_type: retrieval
    metric: retrieval_hit_rate
    modules:
      - module_type: vector_db
        k: [10]
        model_name:
          - avsolatorio/GIST-small-Embedding-v0
          - infgrad/stella-base-en-v2
  - node_type: scoring
    metric: scoring_roc_auc
    modules:
      - module_type: knn
        k: [1, 3, 5, 10]
      - module_type: linear
      - module_type: dnnc
        model_name:
          - BAAI/bge-reranker-base
          - cross-encoder/ms-marco-MiniLM-L-6-v2
        k: [1, 3, 5, 10]
  - node_type: prediction
    metric: prediction_accuracy
    modules:
      - module_type: threshold
        thresh: [0.5]
      - module_type: argmax