# TODO: make up a better and more versatile config
- node_type: retrieval
  metric: retrieval_hit_rate
  search_space:
    - module_name: vector_db
      k: [10]
      embedder_name:
        - avsolatorio/GIST-small-Embedding-v0
        - infgrad/stella-base-en-v2
- node_type: scoring
  metric: scoring_roc_auc
  search_space:
    - module_name: knn
      k: [1, 3, 5, 10]
      weights: ["uniform", "distance", "closest"]
    - module_name: linear
    - module_name: dnnc
      cross_encoder_name:
        - BAAI/bge-reranker-base
        - cross-encoder/ms-marco-MiniLM-L-6-v2
      k: [1, 3, 5, 10]
- node_type: prediction
  metric: prediction_accuracy
  search_space:
    - module_name: threshold
      thresh: [0.5]
    - module_name: argmax